name = "plumbing-site-2"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[cache]
enabled = true

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "edcd7c9f7c344655bfc4149105493e1b"
